/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

USE `biblio`;

UPDATE `ouvrage` AS o
SET `nbre_exemplaire_total` = `nbre_exemplaire` +
	(SELECT COUNT(*) AS nb FROM `pret`
     WHERE o.id = pret.ouvrage_id AND (pret.statut = 'EN_COURS' OR pret.statut = 'PROLONGE' OR pret.statut = 'RETARD'));

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;